import json

from agent.summary_enhance.prompt import PROMPT_VERSION, build_prompt
from agent.summary_enhance.render import render
from agent.summary_enhance.schema import parse_enhanced
from agent.summary_enhance.source_loader import load_guide


def test_prompt_contains_labels_texts_topics_version_and_schema(vault):
    guide = load_guide(vault.guide)
    prompt = build_prompt(guide, ["Wald test", "LM test"])
    for s in guide.sources:
        assert f"[{s.label}]" in prompt and s.text in prompt and s.citation in prompt
    assert "Body text." in prompt
    assert '"Wald test"' in prompt and '"LM test"' in prompt
    assert PROMPT_VERSION in prompt
    assert '"grounded"' in prompt  # schema embedded
    assert "Not from the textbooks" in prompt


def test_prompt_without_topics_asks_model_to_choose(vault):
    prompt = build_prompt(load_guide(vault.guide), [])
    assert "choose" in prompt.lower()


def test_prompt_includes_retry_errors(vault):
    prompt = build_prompt(load_guide(vault.guide), [], errors=["cites unknown label 'S9'"])
    assert "cites unknown label 'S9'" in prompt


def test_render_frontmatter_and_body(vault, good_response):
    guide = load_guide(vault.guide)
    text = render(guide, parse_enhanced(good_response), model="fake-model",
                  generated_at="2026-10-03T12:00:00+00:00")
    front, body = text.split("\n---\n\n", 1)
    assert front.startswith("---\ntitle:")
    assert "llm_generated: true" in front
    assert "content_kind: enhanced_summary" in front
    assert 'enhancement_model: "fake-model"' in front
    assert "prompt_version:" in front and "generated_at: 2026-10-03T12:00:00+00:00" in front
    src = json.loads(next(l for l in front.splitlines() if l.startswith("source_summary: "))[len("source_summary: "):])
    assert src == {"path": "academic_notes/econ/summaries/guide.md", "sha256": guide.sha256}
    refs = json.loads(next(l for l in front.splitlines() if l.startswith("indexer_source_refs: "))[len("indexer_source_refs: "):])
    assert [r["chunk_id"] for r in refs] == ["cam-1", "cam-2", "han-1"]
    assert set(refs[0]) == {"root", "path", "file_id", "chunk_id", "citation"}
    assert refs[0]["root"] == str(guide.root)
    assert json.loads(next(l for l in front.splitlines() if l.startswith("topics: "))[len("topics: "):]) == ["Wald test", "LM test"]

    expected_body = (
        "# Wald and LM tests (enhanced)\n\n"
        "> Generated by `fake-model` from the RAG summary `academic_notes/econ/summaries/guide.md`. "
        "Source-grounded text carries `[S#: citation]` markers; every callout labeled "
        "\"Not from the textbooks\" is LLM elaboration that the textbooks do not support. "
        "Check grounded claims against the cited passages.\n\n"
        "## Wald test\n\n"
        "Both books define the Wald statistic from the unrestricted fit. "
        "[S1: §7.2.3 Wald Test Statistic, p. 249; S3: §9.10 WALD TESTS, p. 268]\n\n"
        "> **Not from the textbooks — LLM elaboration (intuition):** Think of it as a distance in estimate space.\n\n"
        "## LM test\n\n"
        "The LM test needs only the restricted estimator. [S2: §7.3.5 LM test, p. 262]\n\n"
        "## Sources\n\n"
        "- S1: `academic_notes/econ/textbooks/cam.rag.md` (§7.2.3 Wald Test Statistic, p. 249; file_id: `cam`; chunk_id: `cam-1`; corpus: `{root}`)\n"
        "- S2: `academic_notes/econ/textbooks/cam.rag.md` (§7.3.5 LM test, p. 262; file_id: `cam`; chunk_id: `cam-2`; corpus: `{root}`)\n"
        "- S3: `academic_notes/econ/textbooks/han.rag.md` (§9.10 WALD TESTS, p. 268; file_id: `han`; chunk_id: `han-1`; corpus: `{root}`)\n"
    ).replace("{root}", str(guide.root))
    assert body == expected_body


def test_render_lists_only_cited_chunks(vault, good_response):
    good_response["topics"] = good_response["topics"][1:]  # only S2 cited
    guide = load_guide(vault.guide)
    text = render(guide, parse_enhanced(good_response), model="m", generated_at="t")
    assert "chunk_id: `cam-2`" in text
    assert "cam-1" not in text and "han-1" not in text


def test_render_multiline_elaboration_stays_inside_callout(vault, good_response):
    good_response["topics"][0]["elaboration"] = [
        {"kind": "example", "text": "Line one.\n\nLine three."}]
    guide = load_guide(vault.guide)
    text = render(guide, parse_enhanced(good_response), model="m", generated_at="t")
    assert ("> **Not from the textbooks — LLM elaboration (example):** Line one.\n"
            ">\n> Line three.\n") in text
