"""Deterministic Markdown rendering of a validated Enhanced response.
Elaboration is ALWAYS rendered in a 'Not from the textbooks' callout;
the Sources list and indexer_source_refs contain only chunks actually cited."""
from __future__ import annotations

import json

from agent.summary_enhance.prompt import PROMPT_VERSION
from agent.summary_enhance.schema import ElaborationBlock, Enhanced
from agent.summary_enhance.source_loader import GuideInput

GENERATED_BY = "academic-rag-model/agent/summary_enhance/enhance.py"


def _callout(block: ElaborationBlock) -> str:
    lines = block.text.strip().splitlines() or [""]
    head = f"> **Not from the textbooks — LLM elaboration ({block.kind}):** {lines[0]}"
    rest = [f"> {line}" if line.strip() else ">" for line in lines[1:]]
    return "\n".join([head, *rest])


def render(guide: GuideInput, enhanced: Enhanced, *, model: str, generated_at: str) -> str:
    by_label = {s.label: s for s in guide.sources}
    cited: set[str] = {lbl for t in enhanced.topics for g in t.grounded for lbl in g.sources}
    cited_sources = [s for s in guide.sources if s.label in cited]

    refs = [{"root": str(guide.root), "path": s.path, "file_id": s.file_id,
             "chunk_id": s.chunk_id, "citation": s.citation} for s in cited_sources]
    front_fields = {
        "title": json.dumps(f"{guide.title} (enhanced)", ensure_ascii=False),
        "llm_generated": "true",
        "content_kind": "enhanced_summary",
        "generated_by": GENERATED_BY,
        "enhancement_model": json.dumps(model),
        "prompt_version": json.dumps(PROMPT_VERSION),
        "generated_at": generated_at,
        "source_summary": json.dumps({"path": guide.rel_path, "sha256": guide.sha256}),
        "topics": json.dumps([t.title for t in enhanced.topics], ensure_ascii=False),
        "indexer_source_refs": json.dumps(refs, ensure_ascii=False, separators=(",", ":")),
    }
    frontmatter = "---\n" + "".join(f"{k}: {v}\n" for k, v in front_fields.items()) + "---\n\n"

    out = [
        f"# {guide.title} (enhanced)",
        f"> Generated by `{model}` from the RAG summary `{guide.rel_path}`. "
        "Source-grounded text carries `[S#: citation]` markers; every callout labeled "
        "\"Not from the textbooks\" is LLM elaboration that the textbooks do not support. "
        "Check grounded claims against the cited passages.",
    ]
    for topic in enhanced.topics:
        out.append(f"## {topic.title}")
        for block in topic.grounded:
            marks = "; ".join(f"{lbl}: {by_label[lbl].citation}" for lbl in block.sources)
            out.append(f"{block.text.strip()} [{marks}]")
        for block in topic.elaboration:
            out.append(_callout(block))
    source_lines = [
        f"- {s.label}: `{s.path}` ({s.citation}; file_id: `{s.file_id}`; "
        f"chunk_id: `{s.chunk_id}`; corpus: `{guide.root}`)" for s in cited_sources
    ]
    out.append("## Sources\n\n" + "\n".join(source_lines))
    return frontmatter + "\n\n".join(out) + "\n"
